//PersonalStyles.js
export const personalStyles = {
    modalOverlay: "fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50 overflow-y-auto",
    modalContent: "bg-white rounded-lg shadow-xl p-4 sm:p-8 w-full max-w-2xl max-h-[90vh] overflow-y-auto relative",
    mainHeading: "text-x2 sm:text-2xl font-bold text-center mb-4 sm:mb-6 text-black",
    subHeading: "text-lg sm:text-xl font-semibold mb-6 sm:mb-8 text-black",
    form: "space-y-20 sm:space-y-20",
    inputGroup: "relative mb-6 sm:mb-8",
    input: "w-full border-b-2 border-gray-300 py-2 text-black focus:outline-none focus:border-gray-600 transition-colors peer text-base sm:text-lg placeholder-transparent",
    label: "absolute left-0 -top-3 text-gray-600 text-xs sm:text-sm transition-all peer-placeholder-shown:text-base sm:peer-placeholder-shown:text-lg peer-placeholder-shown:top-2 peer-focus:-top-3 peer-focus:text-xs sm:peer-focus:text-sm peer-focus:text-gray-600",
    labelFocused: "-top-3 text-xs sm:text-sm text-gray-600",
    textarea: "w-full border-b-2 border-gray-300 py-2 text-black focus:outline-none focus:border-gray-600 transition-colors peer resize-none min-h-[80px] sm:min-h-[100px] text-base sm:text-lg placeholder-transparent",
    radioGroupContainer: "mb-6 sm:mb-8",
    radioGroupLabel: "block mb-2 sm:mb-3 text-gray-600 text-base sm:text-lg",
    radioGroup: "space-y-2 sm:space-y-3",
    radioLabel: "flex items-center space-x-2 sm:space-x-3 text-black text-base sm:text-lg mb-1 sm:mb-2",
    radioInput: "text-gray-600 focus:ring-gray-600 w-4 h-4 sm:w-5 sm:h-5",
    radioText: "ml-1 sm:ml-2",
    fileInputLabel: "block mb-2 sm:mb-3 text-gray-600 text-base sm:text-lg",
    dropzone: "mt-2 border-2 border-dashed border-gray-300 rounded-md p-4 text-center cursor-pointer hover:border-gray-600 aspect-square flex items-center justify-center w-32 h-32 sm:w-40 sm:h-40 mx-auto",
    fileInput: "hidden",
    navigation: "flex justify-between mt-8 sm:mt-12",
    navButton: "px-4 sm:px-6 py-2 bg-gray-200 text-black rounded hover:bg-gray-300 transition-colors text-base sm:text-lg font-medium",
    closeButton: "absolute top-2 right-2 sm:top-4 sm:right-4 text-gray-600 hover:text-gray-800 transition-colors",
  };